[project]
name = "teagasc-potato-trails-data-pipeline"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.11, <3.12"
dependencies = [
    "pandas>=2.0",
    "numpy>=1.26",
    "pyarrow>=24",
    "openpyxl>=3.1",
    "duckdb==1.5.4",
    "pytest==9.1.1",
    "dlt==1.29.0",
    "pydantic==2.13.4",
    "streamlit==1.59.2",
    "dlt[hub]>=1.0.0",
    "marimo",
    "pyarrow",
    "ibis-framework",
    "dbt-duckdb==1.10.1",
    "dvc==3.67.1",
    "scikit-learn==1.9.0",
    "mlflow==3.14.0",
    "optuna==4.9.0",
    "xgboost==3.2.0",
    "lightgbm==4.7.0"
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0",
    "ruff>=0.4"
]

[tool.ruff]
line-length = 120
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.setuptools.packages.find]
where = ["src"]

[normalize.parquet_normalizer]
add_dlt_load_id = true
add_dlt_id = true

[sources.data_writer]
arrow_concat_promote_options = "permissive"