[project]
name = "teagasc-potato-trials-data-pipeline"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.11, <3.12"

dependencies = [
    "scikit-learn==1.9.0",
    "pandas>=2.0",
    "numpy>=1.26",
    "pyarrow>=24",
    "joblib==1.5.3",
]

[project.optional-dependencies]
data_pipeline = [
    "pyyaml==6.0.2",
    "openpyxl>=3.1",
    "duckdb==1.5.4",
    "dlt==1.29.0",
    "dlt[hub]>=1.0.0",
    "pydantic==2.13.4",
    "streamlit==1.59.2",
    "marimo",
    "ibis-framework",
    "dbt-duckdb==1.10.1",
    "dvc==3.67.1",
    "mlflow==3.14.0",
    "optuna==4.9.0",
    "xgboost==3.2.0",
    "lightgbm==4.7.0",
    "shap==0.51.0"
]
dev = [
    "pytest==9.1.1",
    "ruff>=0.4",
    "jupytext==1.19.5", 
    "seaborn==0.13.2",
    "ipykernel==7.3.0"
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 120
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.setuptools.packages.find]
where = ["src"]

[normalize.parquet_normalizer]
add_dlt_load_id = true
add_dlt_id = true

[sources.data_writer]
arrow_concat_promote_options = "permissive"