paths:
  incoming: data/incoming
  archive: data/archive
  gold: data/gold_versions
  rejects: data/rejects
  artifacts_runs: artifacts/runs
  logs: logs

business_key:
  columns: [year, experiment_name, name1] #Ordered

excel:
  extensions: [.xlsx, .xlsm, .xls]
  default_sheet: 0

always_drop_cols: [barcode_39, block, entry, female,  images, for_yield, hunterl,huntera, hunterb]